const CATEGORIES = [
  {
    id: 1,
    name: '서울',
    subcategories: [
      { subCategoryId: 1, name: '서초/신사/방배' },
      { subCategoryId: 2, name: '잠실/방이' },
      { subCategoryId: 3, name: '강남/역삼/삼성/논현' },
      { subCategoryId: 4, name: '잠실새내/신천' },
      { subCategoryId: 5, name: '영등포/여의도' },
      { subCategoryId: 6, name: '구로/금천/오류/신도림' },
      { subCategoryId: 7, name: '강서/화곡/까치산역/목동' },
      { subCategoryId: 8, name: '천호/길동/둔촌' },
      { subCategoryId: 9, name: '서울대/신림/사당/동작' },
      { subCategoryId: 10, name: '종로/대학로' },
      { subCategoryId: 11, name: '용산/중구/명동/이태원' },
      { subCategoryId: 12, name: '성신여대/성북/월곡' },
      { subCategoryId: 13, name: '노원/도봉/창동' },
      { subCategoryId: 14, name: '강북/수유/미아' },
      { subCategoryId: 15, name: '왕십리/성수/금호' },
    ],
  },
  {
    id: 2,
    name: '경기',
    subcategories: [
      { subCategoryId: 16, name: '수원/인계' },
      { subCategoryId: 17, name: '수원시청/권선/영통' },
      { subCategoryId: 18, name: '수원역/세류/팔달문/구운/장안' },
      { subCategoryId: 19, name: '대부도/제부도' },
      { subCategoryId: 20, name: '안성/평택/송탄' },
      { subCategoryId: 21, name: '오산/화성/동탄' },
      { subCategoryId: 22, name: '파주/금촌/헤이리/통일동산' },
      { subCategoryId: 23, name: '김포/장기/구래/대명항' },
      { subCategoryId: 24, name: '고양/일산' },
      { subCategoryId: 25, name: '의정부' },
      { subCategoryId: 26, name: '부천' },
      { subCategoryId: 27, name: '안양/평촌/인덕원/과천' },
      { subCategoryId: 28, name: '군포/금정/산본/의왕' },
      { subCategoryId: 29, name: '안산' },
      { subCategoryId: 30, name: '광명/철산/시흥신천역' },
    ],
  },
  {
    id: 3,
    name: '인천',
    subcategories: [
      { subCategoryId: 31, name: '부평' },
      { subCategoryId: 32, name: '주안' },
      { subCategoryId: 33, name: '구월/소래포구' },
      { subCategoryId: 34, name: '동암/간석' },
      { subCategoryId: 35, name: '을왕리/인천공항' },
      {
        subCategoryId: 36,

        name: '월미도/차이나타운/신포/동인천',
      },
      { subCategoryId: 37, name: '작전/경인교대' },
      { subCategoryId: 38, name: '용현/숭의/도화/송림' },
      { subCategoryId: 39, name: '송도/연수' },
      { subCategoryId: 40, name: '서구/검단' },
      { subCategoryId: 41, name: '강화/옹진/백령도' },
    ],
  },
  {
    id: 4,
    name: '강원',
    subcategories: [
      { subCategoryId: 42, name: '강릉역/교동택지/옥계' },
      { subCategoryId: 43, name: '경포대/사천/주문진' },
      { subCategoryId: 44, name: '양양/낙산/하조대/인제' },
      { subCategoryId: 45, name: '속초/설악/동명항/고성' },
      { subCategoryId: 46, name: '춘천/홍천/철원/화천' },
      { subCategoryId: 47, name: '원주/횡성' },
      { subCategoryId: 48, name: '정동진/동해/삼척' },
      { subCategoryId: 49, name: '평창/영월/정선/태백' },
    ],
  },
  {
    id: 5,
    name: '제주',
    subcategories: [
      { subCategoryId: 50, name: '제주시' },
      { subCategoryId: 51, name: '애월/협재' },
      { subCategoryId: 52, name: '서귀포/마라도' },
    ],
  },
  {
    id: 6,
    name: '부산',
    subcategories: [
      { subCategoryId: 53, name: '해운대/재송' },
      { subCategoryId: 54, name: '송정/기장/정관' },
      {
        subCategoryId: 55,

        name: '서면/초읍/양정/부산시민공원/범천',
      },
      {
        subCategoryId: 56,

        name: '남포동/부산역/송도/영도/범일동',
      },
      { subCategoryId: 57, name: '광안리/수영/민락' },
      { subCategoryId: 58, name: '경성대/대연/용호/문현' },
      { subCategoryId: 59, name: '동래/온천장/부산대/구서/사직' },
      { subCategoryId: 60, name: '연산/토곡' },
      { subCategoryId: 61, name: '사상(공항경전철)/학장/엄궁' },
      {
        subCategoryId: 62,

        name: '강서/하단/사하/명지/신호/다대포',
      },
      { subCategoryId: 63, name: '덕천/만덕/구포/화명/북구' },
    ],
  },
  {
    id: 7,
    name: '경남',
    subcategories: [
      { subCategoryId: 64, name: '김해/장유/율하' },
      { subCategoryId: 65, name: '양산/밀양' },
      { subCategoryId: 66, name: '거제/통영/고성군' },
      { subCategoryId: 67, name: '진주' },
      { subCategoryId: 68, name: '사천/남해/하동' },
      { subCategoryId: 69, name: '창원 상남/용호/중앙' },
      { subCategoryId: 70, name: '창원 명서/팔용/봉곡/북면' },
      { subCategoryId: 71, name: '마산/진해' },
      { subCategoryId: 72, name: '거창/함안/창녕/합천/의령' },
    ],
  },
  {
    id: 8,
    name: '대구',
    subcategories: [
      { subCategoryId: 73, name: '동성로/시청/서문시장' },
      { subCategoryId: 74, name: '대구역/경북대/엑스코' },
      { subCategoryId: 75, name: '동대구역/신암/신천' },
      { subCategoryId: 76, name: '수성구/수성못/알파시티' },
      { subCategoryId: 77, name: '두류공원/두류/본리/죽전' },
      { subCategoryId: 78, name: '평리/내당/비산/원대' },
      { subCategoryId: 79, name: '성서공단/계명대/달성군' },
    ],
  },
  {
    id: 9,
    name: '경북',
    subcategories: [
      { subCategoryId: 80, name: '경주/보문단지/황리단길' },
      { subCategoryId: 81, name: '구미' },
      { subCategoryId: 82, name: '포항남구/시청/구룡포' },
      { subCategoryId: 83, name: '포항북구/죽도시장' },
      { subCategoryId: 84, name: '울진/울릉도/영덕' },
      { subCategoryId: 85, name: '경산/하양/영천/청도' },
      { subCategoryId: 86, name: '문경/상주/영주/예천' },
      { subCategoryId: 87, name: '안동' },
      { subCategoryId: 88, name: '김천/성주/칠곡/의성' },
    ],
  },
  {
    id: 10,
    name: '울산',
    subcategories: [
      { subCategoryId: 89, name: '동구/북구/일산' },
      { subCategoryId: 90, name: '남구/중구/삼산' },
    ],
  },
  {
    id: 11,
    name: '대전',
    subcategories: [
      { subCategoryId: 91, name: '유성 봉명/도안/장대' },
      { subCategoryId: 92, name: '중구 은행/대흥/선화' },
      { subCategoryId: 93, name: '동구 용전/복합터미널' },
      { subCategoryId: 94, name: '대덕구 신탄진/중리' },
      { subCategoryId: 95, name: '서구 둔산/용문/월평' },
    ],
  },
  {
    id: 12,
    name: '충남/세종',
    subcategories: [
      { subCategoryId: 96, name: '천안 서북구' },
      { subCategoryId: 97, name: '천안 동남구' },
      { subCategoryId: 98, name: '계룡/금산/논산' },
      { subCategoryId: 99, name: '공주/동학사' },
      { subCategoryId: 100, name: '아산' },
      { subCategoryId: 101, name: '태안/안면도' },
      { subCategoryId: 102, name: '서산' },
      { subCategoryId: 103, name: '당진' },
      { subCategoryId: 104, name: '서천/부여' },
      { subCategoryId: 105, name: '대천/보령' },
      { subCategoryId: 106, name: '예산/청양/홍성' },
      { subCategoryId: 107, name: '세종' },
    ],
  },
  {
    id: 13,
    name: '충북',
    subcategories: [
      { subCategoryId: 108, name: '청주 흥덕구/서원구' },
      { subCategoryId: 109, name: '청주 상당구/청원구' },
      { subCategoryId: 110, name: '진천/음성' },
      { subCategoryId: 111, name: '제천/단양' },
      { subCategoryId: 112, name: '충주/수안보' },
      { subCategoryId: 113, name: '증평/괴산/영동/보은/옥천' },
    ],
  },
  {
    id: 14,
    name: '광주',
    subcategories: [
      { subCategoryId: 114, name: '북구/광주역/전남대' },
      { subCategoryId: 115, name: '서구/유스퀘어/상무지구' },
      { subCategoryId: 116, name: '동구/남구/충장로' },
      { subCategoryId: 117, name: '광산구 하남/송정역' },
      { subCategoryId: 118, name: '광산구 첨단지구' },
    ],
  },
  {
    id: 15,
    name: '전남',
    subcategories: [
      { subCategoryId: 119, name: '여수' },
      { subCategoryId: 120, name: '순천' },
      { subCategoryId: 121, name: '광양' },
      { subCategoryId: 122, name: '목포/무안/영암' },
      { subCategoryId: 123, name: '나주/담양/곡성/영광' },
      { subCategoryId: 124, name: '화순/보성/해남/완도' },
    ],
  },
  {
    id: 16,
    name: '전북',
    subcategories: [
      { subCategoryId: 125, name: '전주 덕진구' },
      { subCategoryId: 126, name: '전주 완산구/완주' },
      { subCategoryId: 127, name: '군산/비응도' },
      { subCategoryId: 128, name: '남원/임실/순창' },
      { subCategoryId: 129, name: '익산' },
      { subCategoryId: 130, name: '김제/부안/고창' },
    ],
  },
];

export default CATEGORIES;
